# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=256)),
                ('abstract', models.TextField(verbose_name='abstract')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'article',
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='column_name')),
                ('intro', models.TextField(default='', verbose_name='introduction')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'column',
                'verbose_name_plural': 'column',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='column',
            field=models.ManyToManyField(blank=True, null=True, to='base.Column', verbose_name='belong to'),
        ),
    ]
