# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20170802_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_year',
            field=models.IntegerField(),
        ),
    ]
