# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20170802_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publishment',
            field=models.CharField(default='publishment', max_length=256),
            preserve_default=False,
        ),
    ]
